# Generated by Django 2.1.5 on 2019-03-18 14:21

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issue_a', models.CharField(max_length=100)),
                ('issue_b', models.CharField(max_length=100)),
                ('image_a', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='eithers/images')),
                ('image_b', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='eithers/images')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eithers.Question'),
        ),
    ]
